### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by varunpalekar** [AtomLinter/linter-foodcritic#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-foodcritic](https://github.com/AtomLinter/linter-foodcritic) package, v0.3.5
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /c:/Users/varun/.atom/packages/linter-foodcritic/lib/linter-foodcritic.coffee:44

TypeError: Cannot read property 'replace' of undefined
  at LinterFoodcritic.getCmdAndArgs (C:\Users\varun\.atom\packages\linter-foodcritic\lib\linter-foodcritic.coffee:38:24)
  at LinterFoodcritic.Linter.lintFile (C:\Users\varun\.atom\packages\linter\lib\linter.coffee:122:24)
  at C:\Users\varun\.atom\packages\linter\lib\linter-view.coffee:139:18
  at Array.forEach (native)
  at C:\Users\varun\.atom\packages\linter\lib\linter-view.coffee:138:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-paths",
      "markdown-format"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.2.3
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
git-log, v0.2.0
git-tab-status, v1.4.0
language-chef, v0.4.0
language-docker, v1.1.2
linter, v0.10.0
linter-foodcritic, v0.3.5
linter-ruby, v0.1.4
markdown-stream, v0.6.0
minimap, v3.5.6
minimap-git-diff, v3.1.0
monokai, v0.9.0
remote-sync, v2.3.1
seti-ui, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by c10l** [comment]
Same here.

To reproduce:
1 - Open new tab
2 - Change tab language to Ruby (Control-Shift-L)
3 - :boom: 

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-foodcritic](https://github.com/AtomLinter/linter-foodcritic) package, v0.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/cassiano/.atom/packages/linter-foodcritic/lib/linter-foodcritic.coffee:37

TypeError: Cannot read property 'replace' of undefined
  at LinterFoodcritic.getCmdAndArgs (/Users/cassiano/.atom/packages/linter-foodcritic/lib/linter-foodcritic.coffee:37:24)
  at LinterFoodcritic.Linter.lintFile (/Users/cassiano/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/cassiano/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/cassiano/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:19.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:17.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:14.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:14.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:14.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:13.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.4.0 autocomplete:toggle (atom-text-editor.editor.is-focused)
  2x -0:11 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:11 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:09.7.0 autocomplete:toggle (atom-text-editor.editor.is-focused)
 10x -0:06.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:04.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-outlander-ui",
      "material-design-syntax"
    ],
    "disabledPackages": [
      "vertical-align",
      "open-last-project",
      "term2",
      "autocomplete-ruby",
      "welcome",
      "metrics",
      "language-toml",
      "language-sass",
      "language-perl",
      "language-objective-c",
      "language-less",
      "language-javascript",
      "language-java",
      "language-git",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "keybinding-resolver",
      "language-mustache"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-cli-diff, v0.11.0
atom-color-highlight, v3.0.9
atomatigit, v1.3.0
autocomplete, v0.47.0
autocomplete-paths, v1.0.2
color-picker, v1.7.0
crosshairs, v0.1.2
docs-snippets, v0.8.0
file-watcher, v0.2.1
git-log, v0.3.0
git-projects, v1.13.0
git-tab-status, v1.7.0
highlight-selected, v0.9.2
language-apache, v1.3.0
language-bats, v0.1.0
language-chef, v0.4.0
language-docker, v1.1.3
language-haml, v0.20.0
language-puppet, v0.12.0
language-rspec, v0.3.0
language-ruby, v0.52.0
language-ruby-on-rails, v0.21.0
linter, v0.12.2
linter-erb, v0.1.1
linter-foodcritic, v0.3.7
linter-js-yaml, v1.0.1
linter-jshint, v0.1.4
linter-puppet, v0.1.0
linter-puppet-lint, v0.2.9
linter-puppet-parse, v0.5.0
linter-ruby, v0.1.4
linter-shellcheck, v0.0.7
material-design-syntax, v1.6.0
minimap, v4.8.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
motepair, v0.20.0
one-outlander-ui, v0.3.1
pain-split, v1.4.0
project-colorize, v0.2.0
project-manager, v1.15.5
project-view, v0.1.2
remote-atom, v1.2.6
remote-edit, v1.7.2
rspec-snippets, v0.4.0
ruby-block, v0.3.3
ruby-define-method, v0.2.0
serverspec-snippets, v0.1.0
ssh-config, v0.10.1
sync-settings, v0.2.2
synced-sidebar, v0.2.3
theme-switcher, v1.1.0
trailing-spaces, v0.2.5
you-complete-me, v0.3.2

# Dev
No dev packages
```

**Comment by jarig** [comment]
Should work for Chef syntax files now only
